name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start docker
        run: docker-compose up -d
      - name: Composer install
        run: docker-compose exec -T php bash -c "composer install --no-interaction"
      - name: Waiting db ready
        run: docker-compose exec -T php bash -c 'php -r  "while (true) { try { new PDO(\$_SERVER[\"APP_MYSQL_DSN\"], \$_SERVER[\"APP_MYSQL_USERNAME\"], \$_SERVER[\"APP_MYSQL_PASSWORD\"], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]); exit(0); } catch(\PDOException) { sleep(1); } }"'
      - name: Run unit test
        run: docker-compose exec -T php bash -c "make phpunit_unit"
      - name: Run functional test
        run: docker-compose exec -T php bash -c "make phpunit_functional"
      - name: Behat
        run: make behat